### ISSUE TITLE
Code a program to convert course content to the new platform

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/product-packager#52]
1. Convert relative image paths to absolute paths.

> /courses/$COURSE_FOLDER/$CHAPTER_SLUG/images/$IMAGE_NAME

2. Add Yaml frontmatter at the top of lessons like this:

```yaml
---
title: Importing the project and placing the player character
slug: importing-the-project-and-placing-the-player-character
draft: false
free: false
---
```

3. Add _index.md files inside of the chapter folders with front matter:

```
---
title: Assembling game
slug: assembling-game
---
```

4. Extract nim course builder features

Add SVG icons without the `{=html}` mark
Process include shortcodes

5. Replace links with absolute links

E.g.

> {{ link learn-to-code-how-to-install-godot How to download and run Godot }}
> -> [How to download and run Godot](/course/learn-to-code-from-zero-with-godot/introduction/learn-to-code-how-to-install-godot)

6. Remove HTML comments
